### ISSUE TITLE
Why a separate repo ?

### ISSUE THREAD

**Issue by krazedkrish** [foss-np/Transfer-Fork-Project-Requests#1]
We have a very low number of projects in foss-np. This repo is created so, to encourage developers transfer/fork their repo. in foss-np organization.

Now, if the developers do are not in the admin section. They don't have to make pains to find the Telegram channel, IRC channel or Slack channel or any thing and wait until an admin from this organizations sees the request in facebook or gmail.

In other words, this repo makes the task simple.

**Comment by hardfire** [comment]
Its weird that there is a seperate repostory for this process. Probably its better to have some content regarding this in the foss-np.github.io website and can be solved by using tags in the foss-np.github.com repository. IMO. 
But, a really nice idea definitely !

**Comment by krazedkrish** [comment]
Nice Idea! of adding to foss-np.github.io.
Lets update other things in that site as well.

By the way except that  IRC, is there a separate chat for developers only
like Facebook, Telegram, Slack, or something except IRC.

**Comment by hardfire** [comment]
Yeah! basically i meant that we dont really need a whole repo for this, can just do it in issues of foss-np.github.com repository. And tag/label the items accordingly.

**Comment by krazedkrish** [comment]
well the idea is the issue only related to the site be posted in foss-np.github.com. because new project is not related to site. it is not a relevant place to post issue.

also that way developers watching foss-np.github.com won't be disturbed
and admins handling new projects only won't have to read all the issues in foss-np.github.con to find about new projects.

the idea is filtering signal vs noise.
